import assert from 'node:assert/strict';

export async function checkDraftLifecycle(browser, baseURL) {
  const context = await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/Los_Angeles',serviceWorkers:'block'});
  const page = await context.newPage();
  const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('ybl_state_v3')));
  const nav = name => page.locator('.nav-tab').filter({hasText:name}).click();
  await page.goto(baseURL);
  await page.getByText('Load Demo Roster',{exact:true}).click();
  await page.waitForSelector('.player-item');
  await nav('Game');
  await page.waitForSelector('#game-date');
  const dates = await page.evaluate(() => {
    const format = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
    const d = new Date(), today = format(d); d.setDate(d.getDate()+1); return {today,tomorrow:format(d)};
  });
  await page.getByLabel('Scheduled date').fill(dates.tomorrow);
  await page.getByPlaceholder('Team name (optional)').fill('Tomorrow Tigers');
  const before = (await state()).currentGame;
  assert.equal(before.status,'draft');
  await nav('History'); await nav('Game');
  assert.equal(await page.getByLabel('Scheduled date').inputValue(), dates.tomorrow);
  assert.equal(await page.getByPlaceholder('Team name (optional)').inputValue(),'Tomorrow Tigers');
  assert.equal((await state()).currentGame.id,before.id);
  const sizing = await page.evaluate(() => {
    const d=document.querySelector('#game-date').getBoundingClientRect(), t=document.querySelector('input[placeholder]').getBoundingClientRect();
    return Math.abs(d.width-t.width)<1 && d.right<=innerWidth;
  });
  assert.ok(sizing,'date input aligned with text input');
  await page.getByText('Continue to Lineup →',{exact:true}).click();
  await page.getByText('Start Blank',{exact:true}).click();
  await nav('History'); await nav('Game');
  await page.waitForSelector('.lineup-grid');
  assert.equal(await page.getByText('Start Lineup',{exact:true}).count(),0);
  assert.equal((await state()).currentGame.lineupInitialized,true);
  await page.getByRole('button',{name:'Fill / Re-solve',exact:true}).click();
  const planned = (await state()).currentGame;
  assert.ok(Object.keys(planned.lineup).length>0);
  assert.deepEqual(planned.outs,[]); assert.deepEqual(planned.pitchCounts,{});
  assert.deepEqual((await state()).games,[]);
  await page.reload(); await nav('Game'); await page.waitForSelector('.lineup-grid');
  assert.deepEqual((await state()).currentGame,planned);
  await page.getByText('← Edit Draft / Game Info',{exact:true}).click();
  await page.getByPlaceholder('Team name (optional)').fill('Saturday Tigers');
  await page.getByText('Continue to Lineup →',{exact:true}).click();
  assert.deepEqual((await state()).currentGame.lineup,planned.lineup);
  await nav('Pitchers');
  assert.equal(await page.getByLabel('Eligibility date').inputValue(),dates.today);
  await page.getByLabel('Eligibility date').fill(dates.tomorrow);
  assert.deepEqual((await state()).games,[]);
  await nav('Game'); await page.getByRole('button',{name:'▶ Start Game',exact:true}).click();
  await page.waitForSelector('.live-panel');
  await page.locator('.live-panel button').filter({hasText:'Pitches'}).click();
  for(let i=0;i<5;i++) await page.locator('.pitch-btn-plus').click();
  await page.locator('.pitch-counter-actions button').filter({hasText:'Done'}).click();
  await page.getByRole('button',{name:'⬤ Record Defensive Out',exact:true}).click();
  await page.getByRole('button',{name:'Add run for Our Team',exact:true}).click();
  const live=(await state()).currentGame;
  assert.equal(live.status,'live'); assert.equal(live.outs.length,1); assert.equal(live.score.us[1],1);
  await nav('History'); await page.reload(); await nav('Game'); await page.waitForSelector('.live-panel');
  assert.deepEqual((await state()).currentGame,live);
  await page.getByRole('button',{name:'🏁 Complete Game',exact:true}).click();
  await page.getByRole('button',{name:'Confirm',exact:true}).click();
  await page.locator('.modal-footer button').filter({hasText:'Complete Game'}).click();
  await page.waitForSelector('.card-title:has-text("Game & Workload History")');
  const finished=await state();
  assert.equal(finished.currentGame,null); assert.equal(finished.games.length,1);
  assert.equal(finished.games[0].status,'completed');
  const pitcher=Object.keys(live.pitchCounts)[0];
  assert.equal(finished.games[0].pitchCounts[pitcher].confirmed,5);
  await nav('Pitchers');
  const name=finished.roster.find(p=>p.id===pitcher).name;
  const row=page.locator('.player-item').filter({hasText:name});
  assert.match(await row.textContent(),/Eligible/i,'future completed outing does not affect today');
  await page.getByLabel('Eligibility date').fill(dates.tomorrow);
  assert.doesNotMatch(await row.textContent(),/\bEligible\b/,'appearance on selected date affects eligibility');
  await context.close();
  console.log('OK: mobile scheduled draft persists setup/blank/generated plan, survives reload/edit, starts explicitly, resumes live activity, and completes into date-aware history');
}
